### ISSUE TITLE
Fix TableInvoice glitch for multi denom send

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie-light#179]
The first denom appears repeated for some reason

![image](https://user-images.githubusercontent.com/40721795/98727700-a2e74a00-2398-11eb-81b8-ef9c08b321c2.png)

**Comment by faboweb** [comment]
This is not only table invoice. The error already showed on the details step

**Comment by Bitcoinera** [comment]
OK, will keep an eye

**Comment by Bitcoinera** [comment]
OK, let's do this! :muscle:
