### ISSUE TITLE
Lunie Light: loading logic broken for delegations and balances

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie-light#180]
Since we don't have Apollo anymore, we are displaying the Loading... div based on `balances` and `delegations` length. The problem is that this length is already 0 in `state`.

So for accounts without delegations the Loading... div appears eternally. I think the same is happening for balances, although it should return a `LunieCoin` with `amount: 0`. I will investigate that.

Simple solution: set `balances` and `delegations` and so on to `null` in `state`

**Comment by faboweb** [comment]
Or add a [datapoint]Loaded property which is set to true on first load

**Comment by Bitcoinera** [comment]
you prefer that last option, right? Sounds more elegant, yes. OK, let's do it
