### ISSUE TITLE
Return balance with amount: 0 denom: stakingDenom for accounts with no balance

### ISSUE THREAD

**Issue by Bitcoinera** [luniehq/lunie-light#186]
Pretty self-descriptive issue

**Comment by Bitcoinera** [comment]
Done already: https://github.com/luniehq/lunie-light/blob/c5f7043cbd4e4ab48602d932a0c502812bcf1635/components/common/TableContainer.vue#L21

**Comment by jbibla** [comment]
no no you were right - if there is a balance of 0 but a token in the network config it should show as balance 0 (like in lunie2)

**Comment by Bitcoinera** [comment]
oh ok ok. Let's do it like that then :+1:
