### ISSUE TITLE
logo styling needs to be improved for different image sizes

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#208]
<img width="652" alt="Screen Shot 2020-11-17 at 11 39 40 AM" src="https://user-images.githubusercontent.com/6021933/99419028-a6635f80-28c9-11eb-9d30-b68511bb536d.png">

**Comment by jbibla** [comment]
@mdyring your svg image is large than the actual logo - if you export a new svg without the surrounding transparent box the image will fit better and work nicely on mobile

**Comment by mdyring** [comment]
Done, result visible on wallet.e-money.com. Thanks. :-)
