### ISSUE TITLE
address not appearing on e-money

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#209]
<img width="211" alt="Screen Shot 2020-11-17 at 11 39 51 AM" src="https://user-images.githubusercontent.com/6021933/99419081-b54a1200-28c9-11eb-981a-632932eadf8d.png">

**Comment by mdyring** [comment]
Believe I have fixed that, was a formatAddress issue (I returned type of "emoney" in getAddressType() instead of just sticking with "cosmos").

**Comment by jbibla** [comment]
@faboweb should we refactor formatAddress to use the config file?

**Comment by mdyring** [comment]
Just a suggestion, but instead of calling it a "cosmos" format perhaps just calling it "bech32" format and be done.

Mostly a naming thing, not a biggie IMHO.

**Comment by faboweb** [comment]
We can simplify. It still considers ethereum and polkad addresses
