### ISSUE TITLE
Vesting accounts can't sign

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#215]
user reported:

![image](https://user-images.githubusercontent.com/6021933/99547203-4500c680-2985-11eb-9bec-5ee5fe7b534b.png)

**Comment by faboweb** [comment]
Which user?

**Comment by jbibla** [comment]
@nylira

**Comment by faboweb** [comment]
For which network? for the lunie3 based on cosmoshub-3? Need some more details here

**Comment by faboweb** [comment]
Should be fixed now, was an issue with cosmjs
