### ISSUE TITLE
Transaction amounts not shown

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie-light#219]
Apologies if this is well known - just adding these as I notice it.

Amount it not shown for SendTx but seems with work for withdraw rewards:

![image](https://user-images.githubusercontent.com/18033781/99579231-309ce800-29de-11eb-93d1-0766104fe082.png)

**Comment by faboweb** [comment]
Need to check what goes wrong in `cosmos-reducers` `sendDetailsReducer`

**Comment by faboweb** [comment]
probably a format change from cosmoshub-3 to what you use now

**Comment by mdyring** [comment]
Found it: All the reducers set "amount" instead of "amounts" (plural), with the notable exception of claimRewardsDetailsReducer (which is working)

**Comment by jbibla** [comment]
@Bitcoinera can you confirm this is fixed on lunie-light/master and close / fix...

**Comment by Bitcoinera** [comment]
> @Bitcoinera can you confirm this is fixed on lunie-light/master and close / fix...

OK, let me check

**Comment by Bitcoinera** [comment]
Yes, I cannot check this since we don't have a transactions endpoint anymore with Stargate-4.

Well, I can check in e-Money repo and then check if the same buggy code is in our codebase

**Comment by jbibla** [comment]
fabo added 0.39 reducers yesterday so let's make sure the transaction page works as expected for cosmoshub-3, e-money, akash with 0.39 - don't worry about 0.40.

**Comment by Bitcoinera** [comment]
> fabo added 0.39 reducers yesterday so let's make sure the transaction page works as expected for cosmoshub-3, e-money, akash with 0.39 - don't worry about 0.40.

OK, brilliant. Then I only need to change the `networks.js` file. Amazing
