### ISSUE TITLE
e-Money Ledger login shows right address but shows wrong balances

### ISSUE THREAD

**Issue by jrmoreau** [luniehq/lunie-light#222]
Login process with Ledger seems ok but does not show correct balances once logged in. 

<img width="1515" alt="Screen Shot 2020-11-19 at 12 36 52 PM" src="https://user-images.githubusercontent.com/1614127/99702951-7e5c3380-2a64-11eb-8c9e-9ec6da1c4e40.png">
<img width="1516" alt="Screen Shot 2020-11-19 at 12 41 26 PM" src="https://user-images.githubusercontent.com/1614127/99702983-8c11b900-2a64-11eb-9109-31d466d0ac79.png">

**Comment by Bitcoinera** [comment]
Local accounts have the correct balance

![image](https://user-images.githubusercontent.com/40721795/99716734-c1d89100-2aa8-11eb-9b85-52e25730987f.png)

![image](https://user-images.githubusercontent.com/40721795/99716767-c9983580-2aa8-11eb-889c-748aa975262b.png)

Trying now with Ledger

**Comment by Bitcoinera** [comment]
OK, I saw the problem

**Comment by Bitcoinera** [comment]
Fixed here: https://github.com/e-money/lunie-light/pull/7

**Comment by mdyring** [comment]
Please note there will also be a difference between what Big Dipper shows and Lunie. We have introduced a "spendable" query for accounts, that also takes into consideration the vesting accounts:

http://emoney.validator.network/light/bank/spendable/emoney1q2kc675fw536jq74f6ekwae2pr5pksue22sn3a

**Comment by faboweb** [comment]
Nice! I think it would be a great contribution adding that logic to Lunie directly so others benefit from it as well.

**Comment by jbibla** [comment]
> adding that logic to Lunie directly so others benefit from it as well.

@Bitcoinera can you take care of this?

**Comment by Bitcoinera** [comment]
Can someone please give me a Cosmos vesting account?

**Comment by mdyring** [comment]
Hi guys, the spendable API is not available for Cosmos Hub. I'll fix this for the e-Money chain and use the API.

Generally speaking, I recall seeing a condition in BalanceRow that hides the "available" amount if denom != stakingDenom. This seems like a wrong assumption in most multi-denom scenarios.

**Comment by Bitcoinera** [comment]
> Generally speaking, I recall seeing a condition in BalanceRow that hides the "available" amount if denom != stakingDenom. This seems like a wrong assumption in most multi-denom scenarios.

Can the non-staking tokens be vested? In the example the non-staking token balances are fine. `available` makes sense for staking denoms because they are the only ones that can be staked / vested. Please, correct me if I am wrong

**Comment by mdyring** [comment]
> Can the non-staking tokens be vested? In the example the non-staking token balances are fine. `available` makes sense for staking denoms because they are the only ones that can be staked / vested. Please, correct me if I am wrong

Theoretically, all tokens can be vesting but I am not familiar with any chains that does this with a non-staking token.

I've implemented the spendable API for e-Money, it does not look great on an account with many stablecoins:
![image](https://user-images.githubusercontent.com/18033781/100249738-31cd9800-2f3d-11eb-9de4-d6c14ef736a3.png)

Works better with a vesting account:
![image](https://user-images.githubusercontent.com/18033781/100251667-4dd23900-2f3f-11eb-8100-15e8bb92c79d.png)

**Comment by jbibla** [comment]
> Theoretically, all tokens can be vesting but I am not familiar with any chains that does this with a non-staking token.

true. so we will likely leave this for now. 

> it does not look great on an account with many stablecoins:

what don't you like / do you have ideas for how to improve it?

**Comment by jbibla** [comment]
closing for now as it doesn't seem to be an issue, per se. 

feel free to share thoughts on how we could improve.
