### ISSUE TITLE
Selected fee denom is not propagaged to TX

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie-light#237]
<img width="587" alt="Screenshot 2020-11-23 at 10 42 03" src="https://user-images.githubusercontent.com/18033781/99947789-cc30ae80-2d78-11eb-91e7-fb6d96a4fe30.png">

In the Ledger UI the fee denom is "NGM" (with the expected NGM fee). Seems like denom choice is not propagated.

**Comment by faboweb** [comment]
Confirmed
