### ISSUE TITLE
Lunie extension doesn't connect

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie-light#250]
Merged latest lunie extension changes but can't seem to get the extension to talk with https://beta-wallet.e-money.com.

Any idea/suggestions welcome.

Appears to work on lunie.io... Maybe it is tied to the url? 

<img width="656" alt="Screenshot 2020-11-23 at 22 01 07" src="https://user-images.githubusercontent.com/18033781/100014941-717a6f80-2dd7-11eb-9118-ef57f06b0a7f.png">

**Comment by faboweb** [comment]
Yeah only app.lunie.io is whitelisted in production for now. THe extension will also be discontinued so question is if you really want to have support for it.

**Comment by jbibla** [comment]
we're going to hide the extension except for special cases #253  - e-Money users should use Keplr!
