### ISSUE TITLE
Adding denom to send changes denom of existing line

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie-light#259]
Before - notice "eSEK" denom:
![image](https://user-images.githubusercontent.com/18033781/100103686-81d92b80-2e65-11eb-8ed7-16f2010751e7.png)

After pressing "add" button the "eSEK" changed to NGM. I believe the intention is to preserve it:
![image](https://user-images.githubusercontent.com/18033781/100103749-9d443680-2e65-11eb-9aac-45b761b5b23f.png)

**Comment by faboweb** [comment]
I can't reproduce with 2 denoms only

**Comment by mdyring** [comment]
Odd - can you give it a spin using https://github.com/e-money/lunie-light/blob/master/network.js ?

**Comment by mdyring** [comment]
Fixed in master. Thanks!
