### ISSUE TITLE
SendTx fee denom should default to denom of transaction

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie-light#260]
For a smoother UX, I'd suggest the fee denom defaults to whatever is being sent.

Specifically, it should default to the first (and possibly only) denom in the SendTx.

Demonstrated below:

![image](https://user-images.githubusercontent.com/18033781/100104325-5145c180-2e66-11eb-979f-5cb4c7cee1b4.png)
![image](https://user-images.githubusercontent.com/18033781/100104352-5acf2980-2e66-11eb-8c2a-b149beb46a84.png)

**Comment by faboweb** [comment]
👍  Sounds like a good idea. PR welcome.
