### ISSUE TITLE
Multidenom send fails when checking balance

### ISSUE THREAD

**Issue by mdyring** [luniehq/lunie-light#261]
Even though balance is sufficient, the check seems to fail when sending multiple denoms:

![image](https://user-images.githubusercontent.com/18033781/100105404-9cac9f80-2e67-11eb-984d-35cd9907bc3e.png)

**Comment by faboweb** [comment]
![image](https://user-images.githubusercontent.com/5869273/100108926-54768880-2e39-11eb-9582-07b70ee2784a.png)

could not reproduce

**Comment by mdyring** [comment]
Good news: Can't reproduce anymore either 👍
