### ISSUE TITLE
Error on loading resource: /minting/annual-provisions

### ISSUE THREAD

**Issue by okwme** [luniehq/lunie-light#265]
Hello!
trying out lunie light with a custom chain running. The npx proxy command is great to get around CORs headaches, i remember finding that gem when CORS was a constant danger. my chain is called [pool-toy](https://github.com/interchainberlin/pooltoy) and running v0.39.x. It has the following modules:
```
ModuleBasics    = module.NewBasicManager(
		genutil.AppModuleBasic{},
		auth.AppModuleBasic{},
		bank.AppModuleBasic{},
		staking.AppModuleBasic{},
		distr.AppModuleBasic{},
		params.AppModuleBasic{},
		slashing.AppModuleBasic{},
		supply.AppModuleBasic{},
		pooltoy.AppModuleBasic{},
		faucet.AppModule{},
	)
```
Lunie light is loading on my local dev and connecting to the correct endpoints but i see the following error before anything will render real content:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
webpack-internal:///./apis/cosmos-source.js:171 Error for query minting/annual-provisions in network Pool Toy (tried 3 times)
_callee2$ @ webpack-internal:///./apis/cosmos-source.js:171
webpack-internal:///./node_modules/axios/lib/core/createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at createError (webpack-internal:///./node_modules/axios/lib/core/createError.js:16)
    at settle (webpack-internal:///./node_modules/axios/lib/core/settle.js:17)
    at XMLHttpRequest.handleLoad (webpack-internal:///./node_modules/axios/lib/adapters/xhr.js:61)
```

**Comment by okwme** [comment]
minting isn't required for staking but staking is required for minting... I guess this isn't  very popular configuration but very much so a possible one.

In the current configuration the error cascades to the other parts that are still working, do you think it's possible to fail gracefully in some of the missing module scenarios to preserve other functionality?

**Comment by faboweb** [comment]
It is difficult to consider every configuration of the SDK. It would be better if you customize the cosmos-source and cosmos-reducers files to match your chain.
