### ISSUE TITLE
console errors 

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#274]
visit: https://lunie.cosmos.network/proposals/32

see unhappy console:
<img width="1440" alt="Screen Shot 2020-11-25 at 11 44 41 AM" src="https://user-images.githubusercontent.com/6021933/100257182-a2f85580-2f13-11eb-8457-2fd9f519928b.png">

**Comment by faboweb** [comment]
is that the same in out code base?

**Comment by faboweb** [comment]
#very descriptive title

**Comment by Bitcoinera** [comment]
The CSP are still giving trouble...

**Comment by jbibla** [comment]
i can't reproduce the 404s locally but can on the lunie.cosmos.network version

**Comment by faboweb** [comment]
So it is an issue in the Tendermint Lunie and should be reported and fixed there
