### ISSUE TITLE
Transaction grouping appears without elements

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie-light#278]
![image (6)](https://user-images.githubusercontent.com/5869273/100257694-3762b800-2f14-11eb-9640-d8f31f20eebf.png)

https://lunie.cosmos.network/transactions

Address: cosmos18da7h02z3e46ulee5prg5zl6pr9va0ytv6w46k

**Comment by Bitcoinera** [comment]
This is the Multisend thing, which is already fixed in latest master

**Comment by jbibla** [comment]
yep, confirmed.
