### ISSUE TITLE
Address refactor incompatible with legacy addresses

### ISSUE THREAD

**Issue by faboweb** [luniehq/lunie-light#284]
![image](https://user-images.githubusercontent.com/5869273/100260435-63cc0380-2f17-11eb-8238-0110b34d1b6b.png)

Polkadot addresses from extension are now not trimmed correctly

**Comment by jbibla** [comment]
we should only show addresses that match the chain ID i guess

**Comment by Bitcoinera** [comment]
> we should only show addresses that match the chain ID

Do you mean only extension addresses or in general?

**Comment by Bitcoinera** [comment]
Seems like in extension we are already doing that?

Extension `index.vue` l. 56
```
    filteredAccounts() {
      return this.accounts.filter((account) => account.network === network.id)
    },
```

**Comment by jbibla** [comment]
in the account list, in lunie-light we should only show the addresses from the extension that match the chain-id of lunie-light

**Comment by jbibla** [comment]
fabo closed this here: https://github.com/luniehq/lunie-light/pull/287

**Comment by faboweb** [comment]
THe problem still persists?
