### ISSUE TITLE
automatically signing users in from extension modal

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#285]
it's nice to automatically populate the list, but if there is only 1 i think the user should just click the button instead of redirecting past the modal - creates an uneasy feeling and is a bit jarring.

**Comment by faboweb** [comment]
I think that is already the case...

**Comment by jbibla** [comment]
no i'm saying i don't think we should automatically sign them in

**Comment by faboweb** [comment]
Why? It is the same for Keplr and there it was actually desired to do so
