### ISSUE TITLE
this ledger error is incorrect

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#295]
this was in brave after cancelling the little device popup screen

we can probably just remove it and let the `error` field take care of it

<img width="598" alt="Screen Shot 2020-11-26 at 12 09 27 PM" src="https://user-images.githubusercontent.com/6021933/100378011-621a4280-2fe0-11eb-8299-6d786b925395.png">

**Comment by Bitcoinera** [comment]
> we can probably just remove it and let the `error` field take care of it

What error field do you mean?

This is currently the code:

```
    <div v-if="error" class="error-container">
      <p>There was an error connecting to the Ledger Nano:<br /></p>
      <p class="error">
        {{ error }}
      </p>
    </div>
```

Doesn't look wrong to me :shrug:
